DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS film_likes CASCADE;
DROP TABLE IF EXISTS rating_mpa CASCADE;
DROP TABLE IF EXISTS genres CASCADE;

CREATE TABLE if not exists films (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255),
  description varchar(255),
  release_date date,
  duration int,
  mpa_id int
);

CREATE table if not exists users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) UNIQUE,
  login varchar(255),
  name varchar(255),
  birthday date
);

CREATE table if not exists likes (
  film_id integer,
  user_id integer,
  PRIMARY KEY (film_id, user_id)
);

CREATE table if not exists friends (
  user_id integer,
  friend_id integer,
  status bool,
  PRIMARY KEY (user_id, friend_id)
);

CREATE table if not exists rating_mpa (
  mpa_id INTEGER PRIMARY KEY,
  rating VARCHAR(55)
);

CREATE table if not exists film_genres (
  film_id BIGINT,
  genre_id INTEGER
);

CREATE table if not exists genres (
  genre_id integer PRIMARY KEY,
  genre varchar(55)
);
